FROM ubuntu

RUN  apt-get -y update && \
     apt-get -y install python3  && \
     apt-get -y install python3-pip && \
     pip install pymodbus 

ADD server.py /root/server.py

RUN chmod +x /root/server.py

CMD  ["/root/server.py"]


